---
  - name: Allow ssh in firewall
    action: shell ufw allow ssh

  - name: Allow http in firewall
    action: shell ufw allow http

  - name: Allow https in firewall
    action: shell ufw allow https

  - name: Enable UFW
    action: shell echo 'y' | ufw enable

  - name: Set locale
    command: /usr/sbin/update-locale LANG=${locale} LC_ALL=${locale}

  - name: Set localtime
    command: /bin/cp /usr/share/zoneinfo/${timezone} /etc/localtime

  - name: Set timezone
    template: src=timezone.conf dest=/etc/timezone
    register: tzdata

  - name: Update timezone
    command: dpkg-reconfigure -f noninteractive tzdata
    when: tzdata.changed

  - name: Set hosts
    template: src=hosts.conf dest=/etc/hosts

  - name: Set hostname
    template: src=hostname.conf dest=/etc/hostname

  - name: Set the hostname
    shell: hostname ${hostname}

  - name: Update package cache and install common system packages.
    apt: pkg={{item}} state=installed update-cache=yes
    with_items: "{{common_packages}}"

  - name: Install supervisor
    action: apt pkg=supervisor state=installed 

  - name: Install python-setuptools
    action: apt pkg=python-setuptools state=installed update-cache=no

  - name: Install common system packages.
    apt: pkg=${item} state=installed update-cache=yes
    with_items: ${common_packages}

  - name: Install required role packages.
    apt: pkg=${item} state=installed update-cache=no
    with_items: ${system_packages}

  - name: Create the project directory.
    file: state=directory path={{project_root}}

  - name: Create the project logs directory.
    file: state=directory path={{project_root}}/logs/

  - name: Create ssl group.
    group: name=ssl state=present

  - name: Create user.
    user: home={{project_root}} name={{deployment_name}} shell=/bin/bash state=present groups=ssl

  - name: Copy bash profile to user.
    copy: src=bash_profile  dest={{project_root}}/.bash_profile

  - name: Update the project directory.
    file: group={{deployment_name}} owner={{deployment_name}} mode=755 state=directory path={{project_root}}

  - name: Change permissions.
    shell: chown -R {{deployment_name}}:{{deployment_name}} {{project_root}}
